name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때만 실행됩니다.

permissions:
  contents: write # gh-pages 브랜치에 푸시할 수 있도록 쓰기 권한을 부여합니다.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🏗️ Build Project
        run: npm run build

      - name: 📄 Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
